[package]
name = "tls-tokio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humphrey = { path = "../../humphrey", features = ["tokio", "tls"] }
tokio = { version = "1", features = ["full"] }

[workspace]
